DOCKER_IMAGE_VERSION=latest
DOCKER_IMAGE_NAME=marhan/zenphoto
DOCKER_IMAGE_TAGNAME=$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_VERSION)
PRIVATE_DOCKER_REGISTRY=store:5000
PRIVATE_DOCKER_IMAGE_TAGNAME=$(PRIVATE_DOCKER_REGISTRY)/$(DOCKER_IMAGE_NAME):$(DOCKER_IMAGE_VERSION)

default: build

build:
	docker build -t $(DOCKER_IMAGE_TAGNAME) .

push:
	docker push $(DOCKER_IMAGE_NAME)

private-build:
	docker build -t $(PRIVATE_DOCKER_IMAGE_TAGNAME) .

private-push:
	docker push $(PRIVATE_DOCKER_IMAGE_TAGNAME)